server:
  port: 8088

spring:
#  mvc:
#    view:
#      prefix: /templates/
#      suffix: .html
#      #设定静态文件路径，js,css等
#    static-path-pattern: /js/**
  datasource:
    url: jdbc:mysql://localhost:3306/bxly-tourist?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
#    url: jdbc:mysql://139.199.72.118:3306/bx_travel?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root123
#    password: "@bx123456"
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      test-while-idle: true
      validation-query: select 1
  #thymeleaf start 模板引擎
  thymeleaf:
    # spring.thymeleaf.mode的默认值是HTML5，其实是一个很严格的检查，改为LEGACYHTML5可以得到一个可能更友好亲切的格式要求。
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  #thymeleaf end

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.bx.gis.entity


